CREATE DATABASE IF NOT EXISTS TravelBuddy;
USE TravelBuddy;

CREATE TABLE IF NOT EXISTS Utilizador(
	UtilizadorID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(150) NOT NULL UNIQUE KEY,
    Email VARCHAR(200) NOT NULL UNIQUE KEY,
    PalavraPasse VARCHAR(12) NOT NULL
);