CREATE DATABASE IF NOT EXISTS TravelBuddy;
USE TravelBuddy;

CREATE TABLE IF NOT EXISTS Utilizador(
	UtilizadorID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(150) NOT NULL UNIQUE KEY,
    Email VARCHAR(200) NOT NULL UNIQUE KEY,
    PalavraPasse VARCHAR(12) NOT NULL
);

CREATE TABLE IF NOT EXISTS Voo(
	VooID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CompanhiaAerea VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS RegistoVoo(
	RegistoVooID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    UtilizadorID INT NOT NULL,
    VooID INT NOT NULL,
    DataVoo DATETIME NOT NULL,
    Destino VARCHAR(250),
	NumeroEscala INT NOT NULL,
    Preco DECIMAL NOT NULL,
	FOREIGN KEY(utilizadorID) REFERENCES Utilizador(utilizadorID),
    FOREIGN KEY(vooID) REFERENCES Voo(vooID)
);